In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving Afficionado Coffee Roasters.xlsx to Afficionado Coffee Roasters.xlsx

In [ ]:
import os
print(os.listdir())

['.config', 'Afficionado Coffee Roasters.xlsx', 'sample_data']

In [ ]:
import pandas as pd
filename = list(uploaded.keys())[0]

df = pd.read_excel("Afficionado Coffee Roasters.xlsx")

#print(df)

# display first five row
print(df.head())

# check columns name
print(df.columns.tolist())

#show rows & column count
print(df.shape)

#show columns and missing value
print(df.info())

   transaction_id  year transaction_time  transaction_qty  store_id  \
0               1  2025         07:06:11                2         5
1               2  2025         07:08:56                2         5
2               3  2025         07:14:04                2         5
3               4  2025         07:20:24                1         5
4               5  2025         07:22:41                2         5

    store_location  product_id  unit_price    product_category  \
0  Lower Manhattan          32         3.0              Coffee
1  Lower Manhattan          57         3.1                 Tea
2  Lower Manhattan          59         4.5  Drinking Chocolate
3  Lower Manhattan          22         2.0              Coffee
4  Lower Manhattan          57         3.1                 Tea

            product_type               product_detail
0  Gourmet brewed coffee                  Ethiopia Rg
1        Brewed Chai tea     Spicy Eye Opener Chai Lg
2          Hot chocolate            Dark chocolate Lg
3            Drip coffee  Our Old Time Diner Blend Sm
4        Brewed Chai tea     Spicy Eye Opener Chai Lg
['transaction_id', 'year', 'transaction_time', 'transaction_qty', 'store_id', 'store_location', 'product_id', 'unit_price', 'product_category', 'product_type', 'product_detail']
(149116, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 12.5+ MB
None

In [ ]:
# check missing value
#print(df.isnull())

#check missing value and count
#print(df.isnull().sum())

#check duplicate rows
print(df.duplicated())

#check duplicated rows and count
print(df.duplicated().sum())

#check data type
print(df.dtypes)

0         False
1         False
2         False
3         False
4         False
          ...
149111    False
149112    False
149113    False
149114    False
149115    False
Length: 149116, dtype: bool
0
transaction_id        int64
year                  int64
transaction_time     object
transaction_qty       int64
store_id              int64
store_location       object
product_id            int64
unit_price          float64
product_category     object
product_type         object
product_detail       object
dtype: object

In [ ]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Clean product identifiers
df["product_id"] = df["product_id"].astype("string").str.strip()

##convert price to numeric
df["unit_price"] = pd.to_numeric(
    df["unit_price"],
    errors="coerce"
)

#check missing producet id
print(df["product_id"].isna().sum())

#check missing prices
print(df["unit_price"].isna().sum())

#check total record
print("Total records:", len(df))

#check missing product id
print(
    "Missing product IDs:",
    df["product_id"].isna().sum()
)

#check unit price invalid
print(
    "Invalid prices:",
    (df["unit_price"].isna() |
     (df["unit_price"] <= 0)).sum()
)

# check transaction quantity invalid
print(
    "Invalid quantities:",
    (df["transaction_qty"].isna() |
     (df["transaction_qty"] <= 0)).sum()
)

0
0
Total records: 149116
Missing product IDs: 0
Invalid prices: 0
Invalid quantities: 0

In [ ]:
#  product catalogue
valid_product_ids = {"P101", "P102", "P103"}

df["Unknown_product"] = ~df["product_id"].isin(
    valid_product_ids
)

print(df[["product_id", "Unknown_product"]])

       product_id  Unknown_product
0              32             True
1              57             True
2              59             True
3              22             True
4              57             True
...           ...              ...
149111         44             True
149112         49             True
149113         45             True
149114         40             True
149115         64             True

[149116 rows x 2 columns]

In [ ]:
 #remove duplicate rows
df = df.drop_duplicates()

print("shape after removing duplicated:", df.shape)

# Remove unneccessary sapce from column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print(df.columns.tolist())

shape after removing duplicated: (149116, 12)
['transaction_id', 'year', 'transaction_time', 'transaction_qty', 'store_id', 'store_location', 'product_id', 'unit_price', 'product_category', 'product_type', 'product_detail', 'Unknown_product']

In [ ]:
print("Total transactions:", len(df))
print("Toatal products:", len(df))

Total transactions: 149116
Toatal products: 149116

In [ ]:
#revenue computation
#column name quantity price
df["Revenue"] = df["transaction_qty"] * df["unit_price"]

display(df.head())

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Unknown_product,Revenue
0,1,2025,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,True,6.0
1,2,2025,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,True,6.2
2,3,2025,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,True,9.0
3,4,2025,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,True,2.0
4,5,2025,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,True,6.2

In [ ]:
df["Revenue"] = (
    df["transaction_qty"] * df["unit_price"])


df["transaction_time"] = pd.to_datetime(
    df["transaction_time"].astype(str),
    errors="coerce")


df["hour"] = df["transaction_time"].dt.hour

product_revenue = df.groupby('product_category')['Revenue'].sum() # check product name

print(product_revenue.sort_values(ascending=False))

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Branded                13607.00
Loose Tea              11213.60
Flavours                8408.80
Packaged Chocolate      4407.64
Name: Revenue, dtype: float64

In [ ]:
#calculate revenue
print(df.groupby("product_type")["Revenue"].sum())
print(df.groupby("product_category")["Revenue"].sum())
print(df.groupby("transaction_qty")["Revenue"].sum())
print(df.groupby("unit_price")["Revenue"].sum())

product_type
Barista Espresso         91406.20
Biscotti                 19793.53
Black tea                 2711.85
Brewed Black tea         47932.00
Brewed Chai tea          77081.95
Brewed Green tea         23852.50
Brewed herbal tea        47539.50
Chai tea                  4301.25
Clothing                  6163.00
Drinking Chocolate        2728.04
Drip coffee              31984.00
Espresso Beans            5560.25
Gourmet Beans             6798.00
Gourmet brewed coffee    70034.60
Green beans               1340.00
Green tea                 1470.75
Herbal tea                2729.75
Hot chocolate            72416.00
House blend Beans         3294.00
Housewares                7444.00
Organic Beans             8509.50
Organic Chocolate         1679.60
Organic brewed coffee    37746.50
Pastry                   25655.99
Premium Beans            14583.50
Premium brewed coffee    38781.15
Regular syrup             6084.80
Scone                    36866.12
Sugar free syrup          2324.00
Name: Revenue, dtype: float64
product_category
Bakery                 82315.64
Branded                13607.00
Coffee                269952.45
Coffee beans           40085.25
Drinking Chocolate     72416.00
Flavours                8408.80
Loose Tea              11213.60
Packaged Chocolate      4407.64
Tea                   196405.95
Name: Revenue, dtype: float64
transaction_qty
1    322430.83
2    343529.60
3     28829.10
4       206.80
6       216.00
8      3600.00
Name: Revenue, dtype: float64
unit_price
0.80       8408.80
2.00      17324.00
2.10       2062.20
2.20      19234.60
2.45       9844.10
2.50     100965.00
2.55      10636.05
2.65       1150.10
3.00     151866.00
3.10      26108.20
3.25      20020.00
3.50      63735.00
3.75      92193.75
4.00      17384.00
4.06        267.96
4.25      36754.00
4.38        240.90
4.50      29871.00
4.69        196.98
4.75      21151.75
5.63         84.45
6.40        755.20
7.60       1679.60
8.95       6810.95
9.25       1470.75
9.50       1596.00
10.00      1340.00
10.95      1335.90
12.00      2904.00
13.33      1972.84
14.00      4256.00
14.75      2492.75
15.00      2220.00
18.00      7146.00
19.75      2883.50
20.45      3067.50
21.00      4578.00
22.50      3982.50
23.00       598.00
28.00      6524.00
45.00     11700.00
Name: Revenue, dtype: float64

In [ ]:
#calculate total sold products
product_sales = (
    df.groupby("product_category")["transaction_qty"]
      .sum()
      .reset_index()
)

product_sales.columns = ["Product", "Total_Units_Sold"]

#print(product_sales)
product_sales.head(10)

              Product  Total_Units_Sold
0              Bakery             23214
1             Branded               776
2              Coffee             89250
3        Coffee beans              1828
4  Drinking Chocolate             17457
5            Flavours             10511
6           Loose Tea              1210
7  Packaged Chocolate               487
8                 Tea             69737

In [ ]:
#total units sold per product
product_sales = (
    df.groupby("product_type")["transaction_id"]
    .sum()
      .reset_index()
)

product_sales.columns = ["Product", "Total_Units_Sold"]

#print(product_sales)
product_sales.head(30)

                  Product  Total_Units_Sold
0        Barista Espresso        1229997260
1                Biscotti         423344758
2               Black tea          21925573
3        Brewed Black tea         841577711
4         Brewed Chai tea        1280682019
5        Brewed Green tea         416826124
6       Brewed herbal tea         843226839
7                Chai tea          35168395
8                Clothing          17007018
9      Drinking Chocolate          19845329
10            Drip coffee         637314584
11         Espresso Beans          23103987
12          Gourmet Beans          27923282
13  Gourmet brewed coffee        1269951253
14            Green beans           9215123
15              Green tea          12058142
16             Herbal tea          22338982
17          Hot chocolate         852609712
18      House blend Beans          14012962
19             Housewares          40108921
20          Organic Beans          30980193
21      Organic Chocolate          16596976
22  Organic brewed coffee         630188811
23                 Pastry         515467124
24          Premium Beans          25824880
25  Premium brewed coffee         606564556
26          Regular syrup         378046666
27                  Scone         762497992
28       Sugar free syrup         140132772

In [ ]:
# Rank product sales by volume
product_sales = product_sales.sort_values(
    by="Total_Units_Sold",
    ascending=False
)

product_sales["Sales_Rank"] = (
    product_sales["Total_Units_Sold"]
    .rank(method="min", ascending=False)
    .astype(int)
)

#print(product_sales)
product_sales.head(10)

              Product  Total_Units_Sold  Sales_Rank
2              Coffee             89250           1
8                 Tea             69737           2
0              Bakery             23214           3
4  Drinking Chocolate             17457           4
5            Flavours             10511           5
3        Coffee beans              1828           6
6           Loose Tea              1210           7
1             Branded               776           8
7  Packaged Chocolate               487           9

In [ ]:
#Identify top and bottom performers

top_product = product_sales.loc[
    product_sales["Total_Units_Sold"].idxmax()
]

bottom_product = product_sales.loc[
    product_sales["Total_Units_Sold"].idxmin()
]

print("Top-performing product:", top_product["Product"])
print("Units sold:", top_product["Total_Units_Sold"])

print("\nBottom-performing product:", bottom_product["Product"])
print("Units sold:", bottom_product["Total_Units_Sold"])

NameError: name 'product_sales' is not defined

In [ ]:
# calculate total revenue per product
product_revenue = (
    df.groupby("product_category")["Revenue"]
      .sum()
      .reset_index()
)

product_revenue.columns = ["Product", "Total_Revenue"]

#print(product_revenue)
product_revenue.head(10)

              Product  Total_Revenue
0              Bakery       82315.64
1             Branded       13607.00
2              Coffee      269952.45
3        Coffee beans       40085.25
4  Drinking Chocolate       72416.00
5            Flavours        8408.80
6           Loose Tea       11213.60
7  Packaged Chocolate        4407.64
8                 Tea      196405.95

In [ ]:
#Revenue share (%) of each product
total_revenue = product_revenue["Total_Revenue"].sum()

product_revenue["Revenue_Share_Percent"] = (
    product_revenue["Total_Revenue"] / total_revenue
) * 100

product_revenue["Revenue_Share_Percent"] = (
    product_revenue["Revenue_Share_Percent"].round(2)
)

product_revenue.head(10)

              Product  Total_Revenue  Revenue_Share_Percent
0              Bakery       82315.64                  11.78
1             Branded       13607.00                   1.95
2              Coffee      269952.45                  38.63
3        Coffee beans       40085.25                   5.74
4  Drinking Chocolate       72416.00                  10.36
5            Flavours        8408.80                   1.20
6           Loose Tea       11213.60                   1.60
7  Packaged Chocolate        4407.64                   0.63
8                 Tea      196405.95                  28.11

In [ ]:
#Comparison between volume rank and revenue rank

# Calculate total units sold per product
product_volume = (
    df.groupby("product_type")["transaction_qty"]
      .sum()
      .reset_index()
)

product_volume.columns = ["Product", "Total_Units_Sold"]

# Combine volume and revenue data
comparison = product_volume.merge(
    product_revenue,
    on="Product"
)

# Rank by units sold
comparison["Volume_Rank"] = (
    comparison["Total_Units_Sold"]
    .rank(method="min", ascending=False)
    .astype(int)
)

comparison["Volume_Rank"].head()
# Rank by revenue
comparison["Revenue_Rank"] = (
    comparison["Total_Revenue"]
    .rank(method="min", ascending=False)
    .astype(int)
)

# Sort by volume rank
comparison = comparison.sort_values("Volume_Rank")

comparison.head()

,Product,Total_Units_Sold,Total_Revenue,Revenue_Share_Percent,Volume_Rank,Revenue_Rank
0,Drinking Chocolate,266,72416.0,10.36,1,1

In [ ]:
#Revenue share by category (Coffee, Tea, Chocolate)
# Total revenue for each category
category_revenue = (
    df.groupby("product_category")["Revenue"]
      .sum()
      .reset_index()
)

category_revenue.columns = [
    "Product_Category", "Total_Revenue"
]

# Calculate percentage contribution
total_revenue = df["Revenue"].sum()

category_revenue["Revenue_Share_Percent"] = (
    category_revenue["Total_Revenue"] / total_revenue * 100
).round(2)

# Show highest revenue category first
category_revenue = category_revenue.sort_values(
    "Total_Revenue", ascending=False
)

category_revenue.head(10)

     Product_Category  Total_Revenue  Revenue_Share_Percent
2              Coffee      269952.45                  38.63
8                 Tea      196405.95                  28.11
0              Bakery       82315.64                  11.78
4  Drinking Chocolate       72416.00                  10.36
3        Coffee beans       40085.25                   5.74
1             Branded       13607.00                   1.95
6           Loose Tea       11213.60                   1.60
5            Flavours        8408.80                   1.20
7  Packaged Chocolate        4407.64                   0.63

In [ ]:
#Product-type contribution within each category
# Revenue by category and product type
type_revenue = (
    df.groupby(["product_category", "product_type"])["Revenue"]
      .sum()
      .reset_index()
)

type_revenue.columns = [
    "Product_Category",
    "Product_Type",
    "Type_Revenue"
]

# Total revenue within each category
type_revenue["Category_Total"] = (
    type_revenue.groupby("Product_Category")["Type_Revenue"]
    .transform("sum")
)
# Percentage contribution within the category
type_revenue["Type_Contribution_Percent"] = (
    type_revenue["Type_Revenue"] /
    type_revenue["Category_Total"] * 100
).round(2)

type_revenue.head(30)

,Product_Category,Product_Type,Type_Revenue,Category_Total,Type_Contribution_Percent
0,Bakery,Biscotti,19793.53,82315.64,24.05
1,Bakery,Pastry,25655.99,82315.64,31.17
2,Bakery,Scone,36866.12,82315.64,44.79
3,Branded,Clothing,6163.00,13607.00,45.29
4,Branded,Housewares,7444.00,13607.00,54.71
5,Coffee,Barista Espresso,91406.20,269952.45,33.86
6,Coffee,Drip coffee,31984.00,269952.45,11.85
7,Coffee,Gourmet brewed coffee,70034.60,269952.45,25.94
8,Coffee,Organic brewed coffee,37746.50,269952.45,13.98
9,Coffee,Premium brewed coffee,38781.15,269952.45,14.37
10,Coffee beans,Espresso Beans,5560.25,40085.25,13.87
11,Coffee beans,Gourmet Beans,6798.00,40085.25,16.96
12,Coffee beans,Green beans,1340.00,40085.25,3.34
13,Coffee beans,House blend Beans,3294.00,40085.25,8.22
14,Coffee beans,Organic Beans,8509.50,40085.25,21.23
15,Coffee beans,Premium Beans,14583.50,40085.25,36.38
16,Drinking Chocolate,Hot chocolate,72416.00,72416.00,100.00
17,Flavours,Regular syrup,6084.80,8408.80,72.36
18,Flavours,Sugar free syrup,2324.00,8408.80,27.64
19,Loose Tea,Black tea,2711.85,11213.60,24.18
20,Loose Tea,Chai tea,4301.25,11213.60,38.36
21,Loose Tea,Green tea,1470.75,11213.60,13.12
22,Loose Tea,Herbal tea,2729.75,11213.60,24.34
23,Packaged Chocolate,Drinking Chocolate,2728.04,4407.64,61.89
24,Packaged Chocolate,Organic Chocolate,1679.60,4407.64,38.11
25,Tea,Brewed Black tea,47932.00,196405.95,24.40
26,Tea,Brewed Chai tea,77081.95,196405.95,39.25
27,Tea,Brewed Green tea,23852.50,196405.95,12.14
28,Tea,Brewed herbal tea,47539.50,196405.95,24.20