In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Afficionado Coffee Roasters.xlsx to Afficionado Coffee Roasters (1).xlsx

In [ ]:
filename = list(uploaded.keys())[0]
df = pd.read_excel("Afficionado Coffee Roasters.xlsx")
df.head()

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2025,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2025,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2025,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2025,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2025,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [ ]:
#check column name
df.columns.tolist()

['transaction_id',
 'year',
 'transaction_time',
 'transaction_qty',
 'store_id',
 'store_location',
 'product_id',
 'unit_price',
 'product_category',
 'product_type',
 'product_detail']

In [ ]:
# check size
df.shape

(149116, 11)

In [ ]:
#check missing value and incorrect data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 12.5+ MB

In [ ]:
#show statistic information
df.describe()

,transaction_id,year,transaction_qty,store_id,unit_price,Revenue
count,149116.000000,149116.0,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2025.0,1.438276,5.342063,3.382219,4.686367
std,43153.600016,0.0,0.542509,2.074241,2.658723,4.227099
min,1.000000,2025.0,1.000000,3.000000,0.800000,0.800000
25%,37335.750000,2025.0,1.000000,3.000000,2.500000,3.000000
50%,74727.500000,2025.0,1.000000,5.000000,3.000000,3.750000
75%,112094.250000,2025.0,2.000000,8.000000,3.750000,6.000000
max,149456.000000,2025.0,8.000000,8.000000,45.000000,360.000000

In [ ]:
# check missing value
df.isnull().sum()

transaction_id      0
year                0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
Revenue             0
dtype: int64

In [ ]:
#check duplicated row
df.duplicated().sum()

np.int64(0)

In [ ]:
#remove duplicated
df.drop_duplicates()

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,Revenue
0,1,2025,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00
1,2,2025,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
2,3,2025,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00
3,4,2025,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00
4,5,2025,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2025,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00
149112,149453,2025,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00
149113,149454,2025,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00
149114,149455,2025,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75
149115,149456,2025,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60

In [ ]:
# check data type
df.dtypes

transaction_id               int64
year                         int64
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location              object
product_id          string[python]
unit_price                 float64
product_category            object
product_type                object
product_detail              object
Revenue                    float64
dtype: object

In [ ]:
#convert numiric column
df['transaction_qty'] = pd.to_numeric(
    df['transaction_qty'], errors='coerce'
)

df['unit_price'] = pd.to_numeric(
    df['unit_price'], errors='coerce'
)

In [ ]:
# validate quantity and price
print("Invalid quantities:",
      (df['transaction_qty'] <= 0).sum())

print("Invalid prices:",
      (df['unit_price'] <= 0).sum())

Invalid quantities: 0
Invalid prices: 0

In [ ]:
# check product category
print(df['product_category'].value_counts())

#remove Space
print(df['product_category'].unique())

product_category
Coffee                58416
Tea                   45449
Bakery                22796
Drinking Chocolate    11468
Flavours               6790
Coffee beans           1753
Loose Tea              1210
Branded                 747
Packaged Chocolate      487
Name: count, dtype: int64
['Coffee' 'Tea' 'Drinking Chocolate' 'Bakery' 'Flavours' 'Loose Tea'
 'Coffee beans' 'Packaged Chocolate' 'Branded']

In [ ]:
#remove space and text value
text_columns = [
    'store_location',
    'product_category',
    'product_type',
    'product_detail'
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
# Check product identifiers and required values
print("Missing product IDs:", df['product_id'].isnull().sum())
print("Missing prices:", df['unit_price'].isnull().sum())
print("Missing quantities:", df['transaction_qty'].isnull().sum())

Missing product IDs: 0
Missing prices: 0
Missing quantities: 0

In [ ]:
# calculate Revenue
df['Revenue'] = (
    df['transaction_qty'] * df['unit_price']
)

print(df[['transaction_qty', 'unit_price', 'Revenue']].head())

   transaction_qty  unit_price  Revenue
0                2         3.0      6.0
1                2         3.1      6.2
2                2         4.5      9.0
3                1         2.0      2.0
4                2         3.1      6.2

In [ ]:
# Aggregate revenue  by Product
product_revenue = (
    df.groupby(['product_id', 'product_detail'])
      .agg(
          Total_Units=('transaction_qty', 'sum'),
          Total_Revenue=('Revenue', 'sum')
      )
      .reset_index()
)

print(product_revenue.head())

  product_id                product_detail  Total_Units  Total_Revenue
0          1           Brazilian - Organic          214        3852.00
1         10  Guatemalan Sustainably Grown          134        1340.00
2         11                   Lemon Grass          152        1360.40
3         12                    Peppermint          153        1369.35
4         13             English Breakfast          161        1440.95

In [ ]:
# Aggregate revenue by product type
type_revenue = (
    df.groupby('product_type')['Revenue']
      .sum()
      .reset_index(name='Total_Revenue')
      .sort_values('Total_Revenue', ascending=False)
)
type_revenue.head()

             product_type  Total_Revenue
0        Barista Espresso       91406.20
4         Brewed Chai tea       77081.95
17          Hot chocolate       72416.00
13  Gourmet brewed coffee       70034.60
3        Brewed Black tea       47932.00

In [ ]:
# Aggregate revenue by product category
category_revenue = (
    df.groupby('product_category')['Revenue']
      .sum()
      .reset_index(name='Total_Revenue')
      .sort_values('Total_Revenue', ascending=False)
)

print(category_revenue)

     product_category  Total_Revenue
2              Coffee      269952.45
8                 Tea      196405.95
0              Bakery       82315.64
4  Drinking Chocolate       72416.00
3        Coffee beans       40085.25
1             Branded       13607.00
6           Loose Tea       11213.60
5            Flavours        8408.80
7  Packaged Chocolate        4407.64

In [ ]:
# Product Popularity Analysis
# Total units sold per product

product_popularity = (
    df.groupby(['product_id', 'product_detail'])['transaction_qty']
      .sum()
      .reset_index(name='Total_Units_Sold')
      .sort_values('Total_Units_Sold', ascending=False)
)

product_popularity.head(10)

   product_id               product_detail  Total_Units_Sold
45         50                 Earl Grey Rg              4708
54         59            Dark chocolate Lg              4668
49         54      Morning Sunrise Chai Rg              4643
31         38                        Latte              4602
38         44                Peppermint Rg              4564
21         29    Columbian Medium Roast Rg              4547
47         52    Traditional Blend Chai Rg              4512
32         39                     Latte Rg              4497
14         22  Our Old Time Diner Blend Sm              4484
40         46        Serenity Green Tea Rg              4477

In [ ]:
#  Ranking products by sales volume

product_popularity['Volume_Rank'] = (
    product_popularity['Total_Units_Sold']
    .rank(method='dense', ascending=False)
    .astype(int)
)

product_popularity.head(10)

   product_id               product_detail  Total_Units_Sold  Volume_Rank
45         50                 Earl Grey Rg              4708            1
54         59            Dark chocolate Lg              4668            2
49         54      Morning Sunrise Chai Rg              4643            3
31         38                        Latte              4602            4
38         44                Peppermint Rg              4564            5
21         29    Columbian Medium Roast Rg              4547            6
47         52    Traditional Blend Chai Rg              4512            7
32         39                     Latte Rg              4497            8
14         22  Our Old Time Diner Blend Sm              4484            9
40         46        Serenity Green Tea Rg              4477           10

In [ ]:
# identify top and bottom performers

print("Top 10 popular products:")
print(product_popularity.head(10))

print("Bottom 10 products by units sold:")
print(product_popularity.sort_values(
    'Total_Units_Sold'
).head(10))

Top 10 popular products:
   product_id               product_detail  Total_Units_Sold  Volume_Rank
45         50                 Earl Grey Rg              4708            1
54         59            Dark chocolate Lg              4668            2
49         54      Morning Sunrise Chai Rg              4643            3
31         38                        Latte              4602            4
38         44                Peppermint Rg              4564            5
21         29    Columbian Medium Roast Rg              4547            6
47         52    Traditional Blend Chai Rg              4512            7
32         39                     Latte Rg              4497            8
14         22  Our Old Time Diner Blend Sm              4484            9
40         46        Serenity Green Tea Rg              4477           10
Bottom 10 products by units sold:
   product_id                product_detail  Total_Units_Sold  Volume_Rank
10         19                Dark chocolate               118           75
9          18         Spicy Eye Opener Chai               122           74
1          10  Guatemalan Sustainably Grown               134           73
5          14                     Earl Grey               142           72
62          7         Jamacian Coffee River               146           71
13         21                   Chili Mayan               148           70
44          5        Columbian Medium Roast               148           70
33          4          Primo Espresso Roast               150           69
2          11                   Lemon Grass               152           68
3          12                    Peppermint               153           67

In [ ]:
# Revenue Contribution Analysis
#Total revenue per product

product_revenue['Revenue_Share_Percent'] = (
    product_revenue['Total_Revenue']
    / product_revenue['Total_Revenue'].sum()
    * 100
).round(2)

product_revenue['Revenue_Rank'] = (
    product_revenue['Total_Revenue']
    .rank(method='dense', ascending=False)
    .astype(int)
)

product_revenue = product_revenue.sort_values(
    'Total_Revenue', ascending=False
)

print(product_revenue.head())

   product_id                product_detail  Total_Units  Total_Revenue  \
57         61  Sustainably Grown Organic Lg         4453       21151.75
54         59             Dark chocolate Lg         4668       21006.00
32         39                      Latte Rg         4497       19112.25
35         41                 Cappuccino Lg         4151       17641.75
50         55       Morning Sunrise Chai Lg         4346       17384.00

    Revenue_Share_Percent  Revenue_Rank
57                   3.03             1
54                   3.01             2
32                   2.73             3
35                   2.52             4
50                   2.49             5

In [ ]:
 #compare volume rank and revenue rank
comparison = product_popularity.merge(
    product_revenue[
        ['product_id', 'Total_Revenue',
         'Revenue_Share_Percent', 'Revenue_Rank']
    ],
    on='product_id',
    how='left'
)

print(comparison[
    ['product_id', 'product_detail', 'Total_Units_Sold',
     'Volume_Rank', 'Total_Revenue', 'Revenue_Rank']
].head())

  product_id           product_detail  Total_Units_Sold  Volume_Rank  \
0         50             Earl Grey Rg              4708            1
1         59        Dark chocolate Lg              4668            2
2         54  Morning Sunrise Chai Rg              4643            3
3         38                    Latte              4602            4
4         44            Peppermint Rg              4564            5

   Total_Revenue  Revenue_Rank
0        11770.0            26
1        21006.0             2
2        11607.5            29
3        17257.5             6
4        11410.0            30

In [ ]:
#Category & Product-Type Performance
# Calculate revenue share by category (Coffee, Tea, Chocolate)

category_revenue['Revenue_Share_Percent'] = (
    category_revenue['Total_Revenue']
    / category_revenue['Total_Revenue'].sum()
    * 100
).round(2)

category_revenue

     product_category  Total_Revenue  Revenue_Share_Percent
2              Coffee      269952.45                  38.63
8                 Tea      196405.95                  28.11
0              Bakery       82315.64                  11.78
4  Drinking Chocolate       72416.00                  10.36
3        Coffee beans       40085.25                   5.74
1             Branded       13607.00                   1.95
6           Loose Tea       11213.60                   1.60
5            Flavours        8408.80                   1.20
7  Packaged Chocolate        4407.64                   0.63

In [ ]:
# calculate Product-type contribution within each category

type_category = (
    df.groupby(['product_category', 'product_type'])['Revenue']
      .sum()
      .reset_index(name='Type_Revenue')
)

type_category['Category_Total'] = (
    type_category.groupby('product_category')['Type_Revenue']
                 .transform('sum')
)

type_category['Type_Contribution_Percent'] = (
    type_category['Type_Revenue']
    / type_category['Category_Total'] * 100
).round(2)

type_category.sort_values(
    ['product_category', 'Type_Revenue'],
    ascending=[True, False]
).head(10)

,product_category,product_type,Type_Revenue,Category_Total,Type_Contribution_Percent
2,Bakery,Scone,36866.12,82315.64,44.79
1,Bakery,Pastry,25655.99,82315.64,31.17
0,Bakery,Biscotti,19793.53,82315.64,24.05
4,Branded,Housewares,7444.00,13607.00,54.71
3,Branded,Clothing,6163.00,13607.00,45.29
5,Coffee,Barista Espresso,91406.20,269952.45,33.86
7,Coffee,Gourmet brewed coffee,70034.60,269952.45,25.94
9,Coffee,Premium brewed coffee,38781.15,269952.45,14.37
8,Coffee,Organic brewed coffee,37746.50,269952.45,13.98
6,Coffee,Drip coffee,31984.00,269952.45,11.85

In [ ]:
# Dependence analysis on core categories

category_share = category_revenue.sort_values(
    'Revenue_Share_Percent', ascending=False
)

top_share = category_share.head()['Revenue_Share_Percent'].sum()

print("Revenue share of top  categories:", round(top_share, 2), "%")

Revenue share of top  categories: 94.62 %

In [ ]:
# Revenue Concentration & Menu Balance
#Pareto (80/20) analysis

pareto = product_revenue.sort_values(
    'Total_Revenue', ascending=False
).copy()

pareto['Cumulative_Revenue'] = pareto['Total_Revenue'].cumsum()

pareto['Cumulative_Revenue_Percent'] = (
    pareto['Cumulative_Revenue']
    / pareto['Total_Revenue'].sum() * 100
)

pareto['Product_Number'] = range(1, len(pareto) + 1)

pareto[
    ['product_id', 'product_detail', 'Total_Revenue',
     'Cumulative_Revenue_Percent']
].head(10)

,product_id,product_detail,Total_Revenue,Cumulative_Revenue_Percent
57,61,Sustainably Grown Organic Lg,21151.75,3.026814
54,59,Dark chocolate Lg,21006.00,6.032771
32,39,Latte Rg,19112.25,8.767733
35,41,Cappuccino Lg,17641.75,11.292266
50,55,Morning Sunrise Chai Lg,17384.00,13.779916
31,38,Latte,17257.50,16.249463
29,36,Jamaican Coffee River Lg,16481.25,18.607929
56,60,Sustainably Grown Organic Rg,16233.75,20.930977
34,40,Cappuccino,15997.50,23.220219
19,27,Brazilian Lg,15109.50,25.382387

In [ ]:
# highest performing product
products_for_80 = (
    pareto['Cumulative_Revenue_Percent'] < 80
).sum() + 1

print("Products needed to reach approximately 80% revenue:",
      products_for_80)

Products needed to reach approximately 80% revenue: 43

In [ ]:
# Identify Revenue anchors (few products driving most revenue)
revenue_anchors = pareto[
    pareto['Cumulative_Revenue_Percent'] <= 80
]

print("Revenue anchor products:")
print(revenue_anchors[
    ['product_id', 'product_detail',
     'Total_Revenue', 'Revenue_Share_Percent']
].head(10))

Revenue anchor products:
   product_id                product_detail  Total_Revenue  \
57         61  Sustainably Grown Organic Lg       21151.75
54         59             Dark chocolate Lg       21006.00
32         39                      Latte Rg       19112.25
35         41                 Cappuccino Lg       17641.75
50         55       Morning Sunrise Chai Lg       17384.00
31         38                         Latte       17257.50
29         36      Jamaican Coffee River Lg       16481.25
56         60  Sustainably Grown Organic Rg       16233.75
34         40                    Cappuccino       15997.50
19         27                  Brazilian Lg       15109.50

    Revenue_Share_Percent
57                   3.03
54                   3.01
32                   2.73
35                   2.52
50                   2.49
31                   2.47
29                   2.36
56                   2.32
34                   2.29
19                   2.16

In [ ]:
#Identify Long-tail products
long_tail = pareto[
    pareto['Revenue_Share_Percent'] < 1
]

print("Long-tail products:")
print(long_tail[
    ['product_id', 'product_detail',
     'Total_Revenue', 'Revenue_Share_Percent']
].head(10))

Long-tail products:
   product_id             product_detail  Total_Revenue  Revenue_Share_Percent
68         75                  Croissant        6861.88                   0.98
63         70            Cranberry Scone        6818.44                   0.98
69         76    Chocolate Chip Biscotti        6748.96                   0.97
61         69          Hazelnut Biscotti        6608.01                   0.95
67         74            Ginger Biscotti        6436.56                   0.92
74         81    I Need My Bean! T-shirt        6163.00                   0.88
70         77              Oatmeal Scone        5460.00                   0.78
79          9        Organic Decaf Blend        4657.50                   0.67
55          6                   Ethiopia        4578.00                   0.66
76         83  I Need My Bean! Latte cup        4509.00                   0.65

In [ ]:
# Evaluate menu diversification risk

with pd.ExcelWriter(
    '/content/coffee_roaster_analysis.xlsx',
    engine='openpyxl'
) as writer:

    df.to_excel(writer, sheet_name='Cleaned_Data', index=False)
    product_popularity.to_excel(
        writer, sheet_name='Popularity', index=False
    )
    product_revenue.to_excel(
        writer, sheet_name='Product_Revenue', index=False
    )
    category_revenue.to_excel(
        writer, sheet_name='Category_Revenue', index=False
    )
    type_category.to_excel(
        writer, sheet_name='Type_Performance', index=False
    )
    pareto.to_excel(
        writer, sheet_name='Pareto_Analysis', index=False
    )

    print("Analysis workbook created successfully!")

Analysis workbook created successfully!